[package]
name = "rustgraph"
version = "0.1.0"
authors = ["glcoder0 <glcoder@mail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
